#!/usr/bin/env python3
"""
Pump calibration utility.

Calibrates each peristaltic pump's ``steps_per_ml`` by running it at a known
commanded speed for a known duration and weighing the dispensed liquid on a
serial scale, then writes a JSON config that can be loaded by ``src/config.py``.

How it works
------------
Pumps are driven through an instance of the ``Bioreactor`` class (only the pump
being calibrated is enabled), exactly like ``hardware_testing/od_gui.py`` drives
the LED/OD hardware. Mass is read by a separate ``ScaleReader`` that talks to the
scale over serial. For each trial the script:

    1. reads a stable starting mass,
    2. runs the pump at ``speed`` ml/s for ``duration`` s (via ``change_pump``),
    3. stops the pump and waits ``settle`` s,
    4. reads a stable ending mass.

The Tic velocity that ``change_pump`` issues is ``8 * int(speed * steps_per_ml / 8)``
(see ``src/io.py``). Because that same velocity defines the flow rate, the true
calibration is::

    steps_per_ml = (commanded_velocity * run_seconds) / dispensed_ml

independent of whatever ``steps_per_ml`` was in the config during the run.
Dispensed volume is ``dispensed_mass_g / density_g_per_ml``.

The JSON records the Tic settings used during calibration (step_mode,
current_limit, direction, serial), the fitted ``steps_per_ml``, and the raw
trial data, so a calibration is always traceable to the hardware settings it
was measured under.

Loading the result in src/config.py
-----------------------------------
Add this near the bottom of ``src/config.py`` (after the ``PUMPS`` dict is
defined; the JSON lives next to it in ``src/``)::

    # --- pump calibration (generated by hardware_testing/pump_calibration.py) ---
    import json, pathlib
    _cal_path = pathlib.Path(__file__).with_name('pump_calibration.json')
    if _cal_path.exists():
        _cal = json.loads(_cal_path.read_text())
        for _name, _entry in _cal.get('pumps', {}).items():
            if _name in Config.PUMPS:
                Config.PUMPS[_name]['steps_per_ml'] = _entry['steps_per_ml']

(Each entry under ``"pumps"`` is also a complete ``PUMPS`` entry on its own, so
you can copy a whole block in by hand instead if you prefer.)

Usage
-----
    # Calibrate every pump in Config.PUMPS, 3 trials each at 2.0 ml/s for 30 s:
    python hardware_testing/pump_calibration.py

    # Calibrate just the inflow pump, two speeds, longer runs:
    python hardware_testing/pump_calibration.py --pumps inflow \
        --speeds 1.0,2.0 --duration 45 --replicates 2 --port /dev/ttyUSB0

Requires ``pyserial`` (``pip install pyserial``).
"""

import argparse
import copy
import json
import os
import re
import statistics
import sys
import time
from datetime import datetime
from typing import List, Optional

try:
    import serial  # pyserial
except ImportError:
    print("This script requires pyserial. Install it with: pip install pyserial",
          file=sys.stderr)
    raise

# Add the repo root to the path so we can import the src package, exactly like
# od_gui.py does (this file lives in hardware_testing/).
PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(PARENT_DIR, "src")
sys.path.insert(0, PARENT_DIR)

try:
    from src import Bioreactor, Config
    from src.io import change_pump, stop_pump, stop_all_pumps
except ImportError as e:
    print(
        "Could not import the bioreactor package. On the rig you need a local "
        "src/config.py (copy src/config_default.py to src/config.py and set your "
        f"real pump serial numbers).\nOriginal error: {e}",
        file=sys.stderr,
    )
    raise


# Pololu Tic velocity unit: microsteps (pulses) per 10,000 SECONDS — NOT per
# second. set_target_velocity(V) drives the motor at V / 10,000 microsteps/s.
# See https://www.pololu.com/docs/0J71/5.1 ("speeds in units of pulses per
# 10,000 seconds"). steps_per_ml therefore equals 10,000 x (microsteps per ml).
TIC_VELOCITY_SCALE = 10_000

# ── Defaults ──────────────────────────────────────────────────────────────────
DEFAULT_PORT = "/dev/ttyUSB0"
DEFAULT_BAUDRATE = 9600
DEFAULT_TOLERANCE = 0.001          # g; stability window for a "stable" reading
DEFAULT_READ_TIMEOUT = 1.0         # s; serial read timeout
DEFAULT_READ_BYTES = 18            # bytes to read per 'w' query
DEFAULT_DENSITY = 0.998            # g/mL (water near room temperature)
# Fixed reference used ONLY to turn --speeds (ml/s) into a Tic velocity for the
# test motion. Kept independent of the saved calibration so that re-running the
# calibration commands the same velocity every time (re-runs are reproducible).
DEFAULT_REF_STEPS_PER_ML = 10_000_000.0
DEFAULT_SPEEDS = "2.0"             # ml/s, comma separated
DEFAULT_DURATION = 30.0            # s of pumping per trial
DEFAULT_REPLICATES = 3
DEFAULT_SETTLE = 10.0              # s to wait after stopping before weighing
DEFAULT_PRIME = 60.0               # s; max time to wait for flow while priming
DEFAULT_PRIME_THRESHOLD = 0.05     # g; weight change that means flow reached the scale


def parse_weight(s: str) -> Optional[float]:
    """Parse a float weight from the scale's ASCII output string."""
    m = re.search(r'[-+]?\d*\.\d+|\d+', s)
    return float(m.group()) if m else None


def commanded_velocity(ml_per_sec: float, steps_per_ml: float) -> int:
    """The exact Tic velocity that change_pump issues for a given speed.

    Mirrors the conversion in src/io.py::change_pump so the calibration uses the
    real number of steps the pump executed, including the 8-step rounding.
    """
    return 8 * int(ml_per_sec * steps_per_ml / 8)


def _tic_var(pump, *getter_names):
    """Safely read a Tic variable (e.g. current position) via ticlib.

    Tries each candidate getter name and returns the first that works, or None
    if none are available (so the caller can fall back gracefully).
    """
    for gname in getter_names:
        fn = getattr(pump, gname, None)
        if fn is None:
            continue
        try:
            return fn()
        except Exception:
            return None
    return None


class ScaleReader:
    """Reads a stable weight (grams) from a serial scale.

    The scale is queried by writing ``b'w'`` and reading an ASCII weight back.
    ``read_stable`` returns a value only once ``stable_samples`` consecutive
    readings agree to within ``tolerance`` grams. The serial port is kept open
    across reads and transparently reopened if the connection drops.
    """

    def __init__(self, port: str, baudrate: int = DEFAULT_BAUDRATE,
                 tolerance: float = DEFAULT_TOLERANCE,
                 read_timeout: float = DEFAULT_READ_TIMEOUT,
                 read_bytes: int = DEFAULT_READ_BYTES,
                 stable_samples: int = 2, sample_pause: float = 1.0,
                 max_retries: int = 10, max_samples: int = 120):
        self.port = port
        self.baudrate = baudrate
        self.tolerance = tolerance
        self.read_timeout = read_timeout
        self.read_bytes = read_bytes
        self.stable_samples = max(2, stable_samples)
        self.sample_pause = sample_pause
        self.max_retries = max_retries
        self.max_samples = max_samples
        self._ser: Optional[serial.Serial] = None

    def _ensure_open(self) -> None:
        if self._ser is not None and self._ser.is_open:
            return
        self._ser = serial.Serial(
            port=self.port,
            baudrate=self.baudrate,
            bytesize=serial.EIGHTBITS,
            parity=serial.PARITY_NONE,
            stopbits=serial.STOPBITS_ONE,
            timeout=self.read_timeout,
        )

    def close(self) -> None:
        if self._ser is not None:
            try:
                self._ser.close()
            except Exception:
                pass
            self._ser = None

    def read_once(self) -> Optional[float]:
        """Query the scale once and return the parsed weight (or None)."""
        self._ensure_open()
        try:
            self._ser.reset_input_buffer()
        except Exception:
            pass
        self._ser.write(b'w')
        raw = self._ser.read(self.read_bytes)
        return parse_weight(raw.decode('ascii', errors='ignore'))

    def read_stable(self) -> float:
        """Return a weight once consecutive readings settle within tolerance."""
        recent: List[float] = []
        retries = 0
        samples = 0
        while retries < self.max_retries and samples < self.max_samples:
            try:
                w = self.read_once()
            except (serial.SerialException, OSError) as e:
                print(f"  scale read error: {e}; reconnecting...")
                self.close()
                retries += 1
                time.sleep(1.0)
                continue

            samples += 1
            if w is not None:
                recent.append(w)
                if len(recent) > self.stable_samples:
                    recent.pop(0)
                if (len(recent) == self.stable_samples
                        and (max(recent) - min(recent)) < self.tolerance):
                    return sum(recent) / len(recent)
            time.sleep(self.sample_pause)

        raise RuntimeError(
            f"Scale did not return a stable weight (within {self.tolerance} g) "
            f"after {samples} samples / {retries} reconnects on {self.port}."
        )


def build_pump_config(name: str, entry: dict, command_steps_per_ml: float) -> Config:
    """Make a Config with only the named pump enabled (so only it initializes).

    The pump's steps_per_ml is overridden with ``command_steps_per_ml`` (a fixed
    reference) so the velocity commanded during calibration does NOT depend on
    the currently-saved calibration. That decoupling is what makes re-running the
    calibration reproducible instead of feeding each result back into the next.
    """
    config = Config()
    # Assign fresh dicts so we never mutate the shared class-level attributes.
    config.INIT_COMPONENTS = {k: False for k in Config.INIT_COMPONENTS}
    config.INIT_COMPONENTS['pumps'] = True
    pump_entry = copy.deepcopy(entry)
    pump_entry['steps_per_ml'] = command_steps_per_ml
    config.PUMPS = {name: pump_entry}
    # Calibration only drives the pumps and writes no files: DATA_LOGGING=False
    # suppresses both the data CSV and the results package.
    config.DATA_LOGGING = False
    return config


def run_trial(reactor, scale: ScaleReader, name: str, speed: float,
              duration: float, settle: float, ref_steps_per_ml: float,
              density: float, label: str,
              max_speed: Optional[int] = None) -> Optional[dict]:
    """Run one pump-and-weigh trial; returns a dict of measurements (or None).

    steps_per_ml is derived from the *actual* number of steps the Tic moved (its
    current-position counter) rather than the commanded velocity. The Tic clamps
    the motor to its configured Max speed and ramps through acceleration, so the
    commanded velocity is NOT what the motor actually did; counting real steps
    makes the result immune to clamping, ramping, and timing error.
    """
    pump = reactor.pumps[name]
    velocity = commanded_velocity(speed, ref_steps_per_ml)
    print(f"\n[{label}] speed={speed} ml/s  duration={duration}s  "
          f"(commanded Tic velocity {velocity} = "
          f"{velocity / TIC_VELOCITY_SCALE:g} steps/s)")
    if max_speed is not None and abs(velocity) > max_speed:
        print(f"  WARNING: commanded velocity {velocity} exceeds the device Max "
              f"speed {max_speed}; the Tic will clamp the motor to Max speed. The "
              f"result stays correct (steps are counted), but flow is slower than "
              f"requested — raise Max speed in ticgui or lower --speeds for more "
              f"volume per trial.")

    print("  reading starting mass...")
    mass_before = scale.read_stable()
    print(f"  start: {mass_before:.4f} g")

    pos_before = _tic_var(pump, "get_current_position")
    actual_velocity = None
    t_start = time.monotonic()
    try:
        change_pump(reactor, name, speed)
        time.sleep(duration)
        # Read the Tic's actual current velocity while still running (after the
        # acceleration ramp, and reflecting any Max-speed clamping) for the record
        # and as a fallback if the position counter is unavailable.
        actual_velocity = _tic_var(pump, "get_current_velocity")
    finally:
        stop_pump(reactor, name)
    run_seconds = time.monotonic() - t_start
    pos_after = _tic_var(pump, "get_current_position")
    print(f"  pumped for {run_seconds:.2f} s; settling {settle}s...")
    time.sleep(settle)

    print("  reading ending mass...")
    mass_after = scale.read_stable()
    print(f"  end:   {mass_after:.4f} g")

    delta = mass_after - mass_before
    dispensed_g = abs(delta)
    if dispensed_g < 1e-6:
        print("  WARNING: no measurable mass change; skipping this trial.")
        return None
    dispensed_ml = dispensed_g / density

    # calibration_steps is the numerator such that steps_per_ml = numerator / ml,
    # in the same per-10,000-s convention that change_pump uses.
    steps_moved = None
    if pos_before is not None and pos_after is not None:
        steps_moved = abs(pos_after - pos_before)
    if steps_moved:
        # Exact: position counter is in microsteps; scale to the Tic velocity unit.
        calibration_steps = TIC_VELOCITY_SCALE * steps_moved
        method = "position_counter"
    elif actual_velocity:
        calibration_steps = abs(actual_velocity) * run_seconds
        method = "current_velocity"
    else:
        calibration_steps = abs(velocity) * run_seconds
        method = "commanded_velocity"
        print("  WARNING: could not read the Tic position or velocity; falling "
              "back to the COMMANDED velocity. If the motor was clamped this will "
              "be wrong — check that your ticlib exposes get_current_position / "
              "get_current_velocity.")

    steps_per_ml = calibration_steps / dispensed_ml

    extra = f", steps_moved={steps_moved}" if steps_moved else ""
    print(f"  dispensed {dispensed_g:.4f} g ({'gain' if delta > 0 else 'loss'}) "
          f"= {dispensed_ml:.4f} ml  | method={method}{extra}  ->  "
          f"steps_per_ml = {steps_per_ml:,.1f}")

    return {
        "speed_ml_per_s": speed,
        "commanded_velocity": velocity,
        "actual_velocity": actual_velocity,
        "device_max_speed": max_speed,
        "duration_s": duration,
        "run_seconds": round(run_seconds, 3),
        "steps_moved": steps_moved,
        "measurement_method": method,
        "mass_before_g": round(mass_before, 4),
        "mass_after_g": round(mass_after, 4),
        "dispensed_g": round(dispensed_g, 4),
        "dispensed_ml": round(dispensed_ml, 4),
        "calibration_steps": calibration_steps,
        "steps_per_ml": steps_per_ml,
    }


def prime_until_flow(reactor, scale: ScaleReader, name: str, speed: float,
                     threshold: float, timeout: float) -> bool:
    """Run the pump until the scale weight starts to change (line fully primed).

    Reads a stable baseline, then runs the pump and polls the scale until the
    weight differs from the baseline by ``threshold`` grams on two consecutive
    reads (liquid has reached the vessel), or ``timeout`` seconds elapse. Using
    single reads (not stable reads) because the weight is moving while priming.
    """
    print(f"\nPriming '{name}' at {speed} ml/s until flow is detected "
          f"(>{threshold:g} g change, max {timeout:g}s)...")
    baseline = scale.read_stable()
    print(f"  baseline mass: {baseline:.4f} g")

    w = None
    detected = False
    consecutive = 0
    t_start = time.monotonic()
    try:
        change_pump(reactor, name, speed)
        while (time.monotonic() - t_start) < timeout:
            try:
                w = scale.read_once()
            except (serial.SerialException, OSError) as e:
                print(f"  scale read error during prime: {e}; reconnecting...")
                scale.close()
                time.sleep(0.5)
                continue
            if w is not None and abs(w - baseline) >= threshold:
                consecutive += 1
                if consecutive >= 2:   # confirm, so a single noisy spike won't trip it
                    detected = True
                    break
            else:
                consecutive = 0
            time.sleep(0.2)
    finally:
        stop_pump(reactor, name)

    elapsed = time.monotonic() - t_start
    if detected:
        print(f"  flow detected after {elapsed:.1f}s (now {w:.4f} g); line primed.")
    else:
        print(f"  WARNING: no weight change > {threshold:g} g within {timeout:g}s. "
              f"Check the reservoir/tubing and scale. Continuing anyway.")
    return detected


def calibrate_pump(name: str, entry: dict, scale: ScaleReader, args) -> Optional[dict]:
    """Calibrate a single pump and return its JSON config entry (or None)."""
    print("\n" + "=" * 70)
    print(f"Calibrating pump '{name}'  (serial {entry.get('serial')}, "
          f"step_mode {entry.get('step_mode')}, "
          f"current_limit {entry.get('current_limit')}, "
          f"direction {entry.get('direction')})")
    print("=" * 70)
    print("Set up the tubing so the pump dispenses into (or draws from) a vessel "
          "on the scale.\nInitializing the pump will briefly run it (Tic smoke "
          "test), which also helps prime the line.")
    if not args.no_prompt:
        try:
            input("Press Enter when ready (Ctrl-C to abort)... ")
        except EOFError:
            pass

    config = build_pump_config(name, entry, command_steps_per_ml=args.ref_steps_per_ml)
    reactor = Bioreactor(config, script_path=os.path.abspath(__file__))
    ref_steps_per_ml = args.ref_steps_per_ml
    max_speed = None
    try:
        if not reactor.is_component_initialized('pumps') or name not in getattr(reactor, 'pumps', {}):
            print(f"  ERROR: pump '{name}' failed to initialize (Tic not found?). "
                  f"Skipping.")
            return None

        pump = reactor.pumps[name]
        max_speed = _tic_var(pump, "get_max_speed")
        if max_speed is not None:
            print(f"  device Max speed = {max_speed} "
                  f"({max_speed / TIC_VELOCITY_SCALE:g} steps/s); commanding at a "
                  f"fixed reference of {ref_steps_per_ml:,.0f} steps_per_ml.")
        else:
            print("  NOTE: could not read the device Max speed from ticlib; "
                  "clamping cannot be checked automatically.")

        # Prime the line: run the pump until the scale weight starts to change,
        # so we know liquid has actually reached the vessel and the tube is full.
        if args.prime > 0:
            prime_until_flow(
                reactor, scale, name, args.speeds_list[0],
                threshold=args.prime_threshold, timeout=args.prime,
            )
            time.sleep(args.settle)

        trials: List[dict] = []
        for speed in args.speeds_list:
            for rep in range(args.replicates):
                label = f"{name} {speed}ml/s rep {rep + 1}/{args.replicates}"
                if args.pause_between and not args.no_prompt:
                    try:
                        input(f"  Press Enter to start trial [{label}]... ")
                    except EOFError:
                        pass
                trial = run_trial(
                    reactor, scale, name, speed,
                    duration=args.duration, settle=args.settle,
                    ref_steps_per_ml=ref_steps_per_ml, density=args.density,
                    label=label, max_speed=max_speed,
                )
                if trial is not None:
                    trials.append(trial)
    except KeyboardInterrupt:
        print("\nAborted by user; stopping pump.")
        raise
    finally:
        try:
            stop_all_pumps(reactor)
        except Exception:
            pass
        reactor.finish()

    if not trials:
        print(f"  No valid trials for '{name}'; not writing a calibration.")
        return None

    # Combined estimate: total measured steps / total volume (volume-weighted,
    # through the origin) using the actual steps each trial moved.
    total_steps = sum(t["calibration_steps"] for t in trials)
    total_ml = sum(t["dispensed_ml"] for t in trials)
    steps_per_ml_combined = total_steps / total_ml
    per_trial = [t["steps_per_ml"] for t in trials]
    spml_mean = statistics.fmean(per_trial)
    spml_std = statistics.pstdev(per_trial) if len(per_trial) > 1 else 0.0
    cv_percent = (spml_std / spml_mean * 100.0) if spml_mean else 0.0

    print(f"\n--> pump '{name}': steps_per_ml = {steps_per_ml_combined:,.1f}  "
          f"(mean {spml_mean:,.1f}, spread {cv_percent:.2f}% over {len(trials)} trials)")
    if cv_percent > 5.0:
        print("    NOTE: >5% spread between trials. Consider longer durations, a "
              "primed line, and a settled scale.")

    return {
        "serial": entry.get("serial"),
        "step_mode": entry.get("step_mode"),
        "current_limit": entry.get("current_limit"),
        "direction": entry.get("direction"),
        "steps_per_ml": steps_per_ml_combined,
        "calibration": {
            "generated": datetime.now().isoformat(timespec="seconds"),
            "density_g_per_ml": args.density,
            "command_reference_steps_per_ml": ref_steps_per_ml,
            "tic_velocity_scale": TIC_VELOCITY_SCALE,
            "device_max_speed": max_speed,
            "measurement_methods": sorted({t["measurement_method"] for t in trials}),
            "scale_port": args.port,
            "n_trials": len(trials),
            "steps_per_ml_combined": steps_per_ml_combined,
            "steps_per_ml_mean": spml_mean,
            "steps_per_ml_std": spml_std,
            "steps_per_ml_cv_percent": cv_percent,
            "trials": trials,
        },
    }


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Calibrate pump steps_per_ml by weighing dispensed liquid.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--pumps", default="all",
                   help="Comma-separated pump names to calibrate, or 'all' for "
                        "every pump in Config.PUMPS.")
    p.add_argument("--speeds", default=DEFAULT_SPEEDS,
                   help="Comma-separated commanded speeds in ml/s.")
    p.add_argument("--duration", type=float, default=DEFAULT_DURATION,
                   help="Seconds to run the pump per trial.")
    p.add_argument("--replicates", type=int, default=DEFAULT_REPLICATES,
                   help="Trials per speed.")
    p.add_argument("--settle", type=float, default=DEFAULT_SETTLE,
                   help="Seconds to wait after stopping before weighing.")
    p.add_argument("--prime", type=float, default=DEFAULT_PRIME,
                   help="Max seconds to run the pump while waiting for flow to "
                        "reach the scale during priming (0 to skip priming).")
    p.add_argument("--prime-threshold", type=float, default=DEFAULT_PRIME_THRESHOLD,
                   help="Weight change in grams that signals the line is primed "
                        "(flow has reached the scale).")
    p.add_argument("--density", type=float, default=DEFAULT_DENSITY,
                   help="Liquid density in g/mL for mass->volume conversion.")
    p.add_argument("--ref-steps-per-ml", type=float, default=DEFAULT_REF_STEPS_PER_ML,
                   help="Fixed reference for turning --speeds into a Tic velocity "
                        "during the test. Independent of the saved calibration so "
                        "re-runs command the same velocity (keep it constant).")
    p.add_argument("--port", default=DEFAULT_PORT, help="Scale serial port.")
    p.add_argument("--baud", type=int, default=DEFAULT_BAUDRATE,
                   help="Scale serial baud rate.")
    p.add_argument("--tolerance", type=float, default=DEFAULT_TOLERANCE,
                   help="Stability window in grams for a 'stable' reading.")
    p.add_argument("--stable-samples", type=int, default=2,
                   help="Consecutive readings within tolerance to call it stable.")
    p.add_argument("--output", default=os.path.join(SRC_DIR, "pump_calibration.json"),
                   help="Path to write the calibration JSON.")
    p.add_argument("--pause-between", action="store_true",
                   help="Prompt before each trial (e.g. to re-tare).")
    p.add_argument("--no-prompt", action="store_true",
                   help="Don't wait for Enter between setup steps (unattended).")
    return p.parse_args(argv)


def main(argv=None) -> int:
    args = parse_args(argv)

    try:
        args.speeds_list = [float(s) for s in args.speeds.split(",") if s.strip()]
    except ValueError:
        print(f"Could not parse --speeds '{args.speeds}' as a list of numbers.",
              file=sys.stderr)
        return 2
    if not args.speeds_list:
        print("No speeds given.", file=sys.stderr)
        return 2

    cfg = Config()
    all_pumps = getattr(cfg, "PUMPS", {})
    if not all_pumps:
        print("Config.PUMPS is empty; nothing to calibrate.", file=sys.stderr)
        return 1

    if args.pumps.strip().lower() == "all":
        pump_names = list(all_pumps.keys())
    else:
        pump_names = [n.strip() for n in args.pumps.split(",") if n.strip()]
        missing = [n for n in pump_names if n not in all_pumps]
        if missing:
            print(f"Unknown pump(s): {missing}. Available: {list(all_pumps.keys())}",
                  file=sys.stderr)
            return 2

    print(f"Calibrating pump(s): {pump_names}")
    print(f"Speeds: {args.speeds_list} ml/s | duration {args.duration}s | "
          f"{args.replicates} replicate(s) | settle {args.settle}s | "
          f"density {args.density} g/mL")
    print(f"Scale on {args.port} @ {args.baud} baud, tolerance {args.tolerance} g")

    scale = ScaleReader(
        port=args.port, baudrate=args.baud, tolerance=args.tolerance,
        stable_samples=args.stable_samples,
    )

    # Start from any existing calibration so we only overwrite the pumps we redo.
    out = {"generated": None, "density_g_per_ml": args.density, "pumps": {}}
    if os.path.exists(args.output):
        try:
            with open(args.output) as f:
                existing = json.load(f)
            if isinstance(existing.get("pumps"), dict):
                out["pumps"] = existing["pumps"]
        except Exception as e:
            print(f"Could not read existing {args.output} ({e}); starting fresh.")

    results = {}
    try:
        for name in pump_names:
            entry = calibrate_pump(name, all_pumps[name], scale, args)
            if entry is not None:
                results[name] = entry
    except KeyboardInterrupt:
        print("\nInterrupted.")
    finally:
        scale.close()

    if not results:
        print("\nNo calibrations were produced; leaving output file unchanged.")
        return 1

    out["pumps"].update(results)
    out["generated"] = datetime.now().isoformat(timespec="seconds")

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        json.dump(out, f, indent=2)
    print(f"\nWrote calibration for {list(results.keys())} to {args.output}")

    print("\nResults:")
    for name, entry in results.items():
        print(f"  {name}: steps_per_ml = {entry['steps_per_ml']:,.1f}")
    print("\nTo use it, add this to the bottom of src/config.py:\n"
          "    import json, pathlib\n"
          "    _cal_path = pathlib.Path(__file__).with_name('pump_calibration.json')\n"
          "    if _cal_path.exists():\n"
          "        _cal = json.loads(_cal_path.read_text())\n"
          "        for _name, _entry in _cal.get('pumps', {}).items():\n"
          "            if _name in Config.PUMPS:\n"
          "                Config.PUMPS[_name]['steps_per_ml'] = _entry['steps_per_ml']")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
